### ISSUE TITLE
need one central version / repo

### ISSUE THREAD

**Issue by pljakobs** [pkourany/Arduino_Adafruit_mfGFX_Library#2]
Not sure why there are different versions for different displays, maybe even different functionality.
Can we merge them all?

**Comment by pkourany** [comment]
@pljakobs, not sure what you mean.  The only two versions are for the Particle platform and Arduino.  I kept them separate on purpose until a better library model is implemented by Particle.

**Comment by pljakobs** [comment]
when I search for Adafruit_mfGFX, I find some for sharp displays, some for ST7735 and a few more, but maybe I'm just confused, in that case disregard and makr as resolved, please.

**Comment by pkourany** [comment]
@pljakobs, actually you are correct.  Those libs were created "on the fly" to work with mfGFX and would benefit from NOT having the mfGFX library files.  Some libs are used in the Particle web IDE and some are standalone.  I'll have to consider a cleanup at some point.
