### ISSUE TITLE
flexible font lists

### ISSUE THREAD

**Issue by pljakobs** [pkourany/Arduino_Adafruit_mfGFX_Library#3]
I'll try to make the font handling a bit more flexible
that should mean a dynamic, readable global list of available font faces and sizes so a program can change face independently of size and size independently of face, for example to adapt to screen size.
Currently, I'm forced to do this in a very strange way

``` Arduino
    String strTime=getTimeString(TIME_VERBAL);
      tft.setFont(ARIAL_36);
      tft.setTextWrap(0);
      if(tft.getStringWidth(strTime)>screen_width){
        tft.setFont(ARIAL_24);
        if(tft.getStringWidth(strTime)>screen_width){
          tft.setFont(ARIAL_16);  
          if(tft.getStringWidth(strTime)>screen_width) tft.setTextWrap(1);
        }
      }
```

**Comment by pkourany** [comment]
@pljakobs, sounds great!  The only catch is that you have to have all the font sizes defined and loaded.  But I like the idea of setting the default font then specifying the size as required.

**Comment by pljakobs** [comment]
I'm thinking of changing the fonts.cpp format to something less static like:

``` c++
uint16_t i;
const unsigned char font_Bitmaps[i] PROGMEM =
{
...
}

const FontDescriptor font_Descriptor[i++] PROGMEM =
{
...
}

```

plus an array describing Fontface and Size for ever [i]

let's see :-)

**Comment by pkourany** [comment]
The primary reason for the existing font tables was the output of the program used to generate the font files.  It uses KISS so any user can easily create and import their own fonts.  There is no question the format is not optimal but it is easy to generate and use.  As for the fontface and size array, you could populate that based on the #defines that enables the fonts for compilation.

**Comment by pljakobs** [comment]
understood
