### ISSUE TITLE
external font files

### ISSUE THREAD

**Issue by pljakobs** [pkourany/Arduino_Adafruit_mfGFX_Library#4]
many displays come with an sdcard slot attached to them, so having external data is often an option.
The font handling currently relies on having all the fonts in PROGMEM at compile time.
It should be possible to extend the library to load the required (and only the required) fonts from sdcard at runtime. That will require some change to the data structures (as I wrote in the other issue I've opened). I'll give it a shot, but am not at all certain that I can do it. For starters, it would require defining a font file format and I would not like to re-invent the wheel but use the normal Windows (or Linux) raster fonts. Let's see.

**Comment by pkourany** [comment]
@pljakobs, the biggest issue with defining SD-based fonts is the speed.  Pulling fonts via SPI is nowhere need the speed of flash, especially if you only buffer a line at a time in RAM.  Using RAM to cache the whole font is often not feasible for larger fonts.  I look forward to seeing your approach.

**Comment by pljakobs** [comment]
argh! it just appeared to me that we can't write to PROGMEM at runtime... 
silly me, too much desktop thinking :o
So they would consume valuable RAM.
Or would have to be loaded glyph by glyph, which is probably dog slow as you said.

**Comment by pkourany** [comment]
Yup, slow as heck.  I wrote an library for a Sharp Memory display that used SPI FRAM as a display buffer since the Particle Core it was designed for did not have enough RAM.  Let's just say it was not ideal performance but it worked!

**Comment by pljakobs** [comment]
I wonder if the SPI hardware on Teensy3.1/3.2 will make a difference here. It's quite a bit faster than on a standard Arduino, but the card will have to play nicely, too.
I'll try.
Anyway, I'm just opening those issues so I can track them somewhere for my own purposes and so that, if someone else cares to work on them, it's visible.

**Comment by pkourany** [comment]
@pljakobs, with creative use of SPI DMA, you could transfer an entire char block to a display buffer directly.  However, mfGFX doesn't work that way since you have to apply color to the pixel data.  The library uses the drawPixel() at the lowest level.  This approach is great for a generalized graphics library but not so much for using SPI and DMA.

The only possible efficiency is to use SPI DMA to transfer the entire character to RAM and "parse" it from there.
