### ISSUE TITLE
international character sets

### ISSUE THREAD

**Issue by pljakobs** [pkourany/Arduino_Adafruit_mfGFX_Library#5]
as a German, I would love to be able to use the "usual" German Umlauts such as äöüÄÖÜß
but I know that the chinese will be follwing right behind and we'll soon be talking about unicode enabling this :o scary.

**Comment by pkourany** [comment]
@pljakobs, you are giving me a headache now!  Though I enjoyed modding the GFX library for multiple fonts, I am not sure it's the right platform to expand that way.

**Comment by pljakobs** [comment]
I know, and I wasn't suggesting unicode, I just played with some German Text today (actually, just outputting the time in word form) and the German word "zwölf" (for twelve) came out butchered (zwlf, since there's no glyph for the "ö").
Adding the seven additional German characters would be simple enough (although it would mean discontinuous fonts), but then everybody else can demand the same thing with the Chinese or Arabs or Greek and Russian being the farthest from what it is today. 
One option would be to just extend the character set to beyond 0x7f and use those. Wonder what code page Arduino uses to map those characters.
some reference:
[utf-8 in Arduino](http://playground.arduino.cc/Code/UTF-8)
[non-us ASCII](http://www.visualmicro.com/page/User-Guide.aspx?doc=Non-ASCII.html)

**Comment by pljakobs** [comment]
Spent quite a bit of time yesterday trying to understand how to best print international characters.
ThePixelFactory does embed extended characters into the consumable font if asked to, however, since the character index is positional, it's not quite clear to me where specific characters go. 
I'm currently looking at freetype to easily create the same font format but additionally a character map that would allow me to use codepages like in DOS or even directly use utf-8. The latter would be the better way, since Arduino Strings handle utf-8 just fine and I would not have to mock about with translating codepages (I have written a function to translate utf-8 to cp850, but it's not elegant).
On the other hand, utf-8 fonts would be quite large, depending on how many extra characters they contain.

**Comment by pljakobs** [comment]
@pkourany I have written a small c-program that will use FreeType to create the required font sets.
In order to easier render them and save some memory, however, I would have to slightly change the FontDescriptors

``` c
  typedef struct _FontDescriptor {
    int         xMin;
    int         xMax;
    int         yMin;
    int         yMax;
    int         advance;
    int         unicode;
    int         offset;
  } FontDescriptor;
```

in code, this would look like this:

``` c
const FontDescriptor Open Sans_Regular_16ptDescriptors2[] PROGMEM = {
  {0x00, 0x0e, 0xffffffff, 0x0c, 0x0000},
  {0x00, 0x0a, 0x00, 0x0c, 0x001a},
  {0x01, 0x0a, 0x00, 0x0c, 0x0032},
  {0x00, 0x0a, 0x00, 0x0c, 0x004a},
  {0x01, 0x0b, 0x00, 0x0c, 0x0062},
  {0x01, 0x09, 0x00, 0x0c, 0x007a},
  {0x01, 0x08, 0x00, 0x0c, 0x0086},
  {0x01, 0x0b, 0x00, 0x0c, 0x0092},
  {0x01, 0x0b, 0x00, 0x0c, 0x00aa},
  {0x01, 0x03, 0x00, 0x0c, 0x00c2},
```

This is the actual Bitmap portion:

``` c
const unsigned char Open Sans_Regular_16ptBitmaps[] PROGMEM = {
0x07, 0x80, 0x18, 0x40, 0x30, 0x20, 0x23, 0x10, 0x44, 0x90, 0x48, 0x90, 0x48, 0x90, 0x48, 0x10, 0x4c, 0xa0, 0x47, 0xe0, 0x20, 0x00, 0x10, 0x80, 0x0f, 0x80, // 0x40,@
0x0c, 0x00, 0x0c, 0x00, 0x0c, 0x00, 0x12, 0x00, 0x12, 0x00, 0x33, 0x00, 0x21, 0x00, 0x3f, 0x00, 0x61, 0x00, 0x40, 0x00, 0x40, 0x00, 0xc0, 0x80, // 0x41,A
0x7c, 0x00, 0x46, 0x00, 0x43, 0x00, 0x43, 0x00, 0x42, 0x00, 0x7c, 0x00, 0x42, 0x00, 0x41, 0x00, 0x41, 0x00, 0x41, 0x00, 0x43, 0x00, 0x7c, 0x00, // 0x42,B
0x0f, 0x00, 0x18, 0x00, 0x30, 0x00, 0x60, 0x00, 0x60, 0x00, 0x40, 0x00, 0x40, 0x00, 0x60, 0x00, 0x60, 0x00, 0x20, 0x00, 0x38, 0x00, 0x0f, 0x00, // 0x43,C
0x7e, 0x00, 0x43, 0x00, 0x41, 0x00, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x41, 0x00, 0x43, 0x00, 0x7e, 0x00, // 0x44,D
0x7e, 0x40, 0x40, 0x40, 0x40, 0x7e, 0x40, 0x40, 0x40, 0x40, 0x40, 0x7e, // 0x45,E
0x7e, 0x40, 0x40, 0x40, 0x40, 0x40, 0x7c, 0x40, 0x40, 0x40, 0x40, 0x40, // 0x46,F
0x1f, 0x00, 0x30, 0x00, 0x60, 0x00, 0xc0, 0x00, 0xc0, 0x00, 0x80, 0x00, 0x83, 0x80, 0xc0, 0x80, 0xc0, 0x80, 0x60, 0x80, 0x30, 0x80, 0x1f, 0x00, // 0x47,G
0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x7f, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, // 0x48,H
0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, // 0x49,I
0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x10, 0x60, // 0x4a,J
0x41, 0x00, 0x42, 0x00, 0x46, 0x00, 0x4c, 0x00, 0x58, 0x00, 0x70, 0x00, 0x78, 0x00, 0x4c, 0x00, 0x44, 0x00, 0x42, 0x00, 0x43, 0x00, 0x41, 0x00, // 0x4b,K
0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x7e, // 0x4c,L
```

FreeType uses the concept of a Bounding Box and the xMin,xMax,yMin,yMax describe the position of a character in the bounding box. This way, a character bitmap does not have to describe all the bits in the character cell. The values for the bounding box can also be negative. (and currently, I'm not writing out advance and unicode. Still thinking if I need them)
Quite obviously, this change would render Adafruit_mfGFX no longer backwards compatible (albeit, we might just be able to define this as an alternative format...)
I'm probably going to implement those changes in my fork for now and create a pull request once I have something working.
pj

**Comment by pkourany** [comment]
@pljakobs, I like it!!  The font descriptor table gets bigger but at the benefit of the bitmap getting smaller.  With the bounding box concept, characters can be different heights and dip below the base line so how do you propose doing line feed/spacing?

I'm not clear what advance and offset do.  As for the backwards compatibility, I would create a new branch entirely, like ftGFX for freetype GFX as an example.  Users could chose how they create fonts and pick the corresponding library. The only difference will be the font handling.

**Comment by pljakobs** [comment]
@pkourany I've just pulled the xAdvance and yAdvance values into the font descriptors. They are the character / line advances. The offset is, as it was so far, the offset into the font bitmap, which itself is unstructured as it was before iirc.
Hope to have a running prototype by tonight :) Right now, I'm working on putting in some font info (such as family, regular/bold/italics, serif/sans as well as iso8859-1 -11 code pages.
The result would be that a user could a) define a codepage and the correct character set would be loaded (192 characters at a time) and, ideally, selecting fonts by type / attributes should be doable (like: I want a bold face sans serif font at 16pt and the system checks if there's one included. Could be Helvetica, Arial or Liberation_Sans). Also, I belive that there's a set of fonts that could be shipped with the library (like Liberation) because they're under a free license.
Another Idea I'm playing with is a text bounding box. I have created that small call that gives me the running length of a snippet of text. I'm thinking about a set of calls that a) return the Rect coordinates for the box necessary for this text and b) maybe return a "best fit" font / size for a given Rect (think displaying a dashboard (happens to be my application) with fixed cells for information - how do I best visualize what I need there in a world that has different characters?)

**Comment by pkourany** [comment]
@pljakobs, I would love to see the amount of bytes taken by a given font & size for the existing mfGFX tables vs that of the ftGFX tables.

As for the best fit font in a bounding box, I tend to be very picky about the look and feel of my interfaces so I will pick a font & size as part of the design and not at runtime.

Great work!

**Comment by pljakobs** [comment]
@pkourany I would assume that ftGFX fonts will be larger for fonts <=10pt in size since the font descriptor table is now 10 rather than just four bytes in size. 
Also keep in mind that my primary goal is to provide full ISO8859-x character sets, that is, the fonts will have 256 character slots, of which usually only 64 will not be populated. In essence, a tfGFX font will be larger in most cases.

Working from the Tables:

| Font File | pt Size | Format | # of chars | Bitmaps | Descriptors | overal size | bytes per char |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Liberation Sans Regular | 8pt | ftGFX | 192 | 1120 | 2240 | 3360 | 17 |
| Arial | 8pt | mfGFX | 95 | 990 | 380 | 1370 | 14 |
| Liberation Sans Regular | 16pt | ftGFX | 192 | 2910 | 2240 | 5150 | 26 |
| Times | 16pt | mfGFX | 95 | 3021 | 380 | 3401 | 35 |
| Liberation Sans Regular | 36pt | ftGFX | 192 | 10985 | 2250 | 13235 | 68 |
| Arial | 36pt | mfGFX | 95 | 13301 | 380 | 13681 | 140 |

So from a purely theoretical view, ftGFX fonts use "just" 3 bytes per character more for 8pt fonts than a mfGFX font and from there on, with larger fonts, get gradually better until they use about half as much space for 36pt fonts.
The format seems therefore to be much more suitable for larger (or higher density) displays.
For my Application, I will at least use 12pt fonts, so I think it'll be at worst on par, realistically they'll be a tad better.

I'm glad that I'm working on a teensy 3.1/3.2 platform that has ample PROGMEM (256k) :D

(that's all provided I get it to work ;-) )

oh, almost forgot: I also use one 512 byte array for 8859-x to utf-8 encoding, albeit not per font but per encoding, so probably just one for any given program. I'm sure there's a better way (there certainly is for 8859-1), but that has to be seen. Optimizations come later.

**Comment by pljakobs** [comment]
@pkourany I'm pushing my intermediates to https://github.com/pljakobs/Adafruit_ftGFX/tree/devel 
there's still a lot to do, it has to be said, currently I cannot set even a signle pixel, but if you're interested to have a look at the way it's shaping up, I'd be thankful for any input. It is, however, a bit of a mess, still.

Also, I stumbled over something that you might have an answer to: there's an include for Adafruit_GFX in the actual driver library (Adafruit_ST7735.h). No matter if I include ftGFX before ST7735 or not, no matter if I define _ADAFRUIT_GFX_H or not, the driver library want's to include Adafruit_GFX.h again and fails unless I "correct" it to include Adafruit_ftGFX - do you have an idea how to solve that a bit more elegant?

**Comment by pkourany** [comment]
Where are you pulling Adafruit_ST7735.h from?  You need to look at all the files to see which one is pulling in Adafruit_GFX.h

**Comment by pljakobs** [comment]
I have reached a useful state with ftGFX, if you want to go ahead and close this issue @pkourany, that'll be ok. Thanks for your work and help
If you have any time to test ftGFX, as said, feedback is highly appreciated.

pj

**Comment by pljakobs** [comment]
I think I'll have to face the fact that the ft fonts are quite a bit larger than what I have initially calculated. Adding Open Sans Bold 36pt adds no less than 33032 bytes to the compiled size of the program. That's quite hefty.

**Comment by pkourany** [comment]
@pljakobs, that sucks!  Fonts and graphics take up a lot of room.  This is why I consider using HMI displays (eg. Nextion) or Digole displays that offload most if not all of that. :)

**Comment by pljakobs** [comment]
yeah, I know, but then again, I won't need a whole slew of fonts and I have 256k of progmem available. Why not live some luxury ;-)
At least by now, I can properly display all relevant european characters in latin-1 and that was the goal :-)
