### ISSUE TITLE
Arduino Due compile problem

### ISSUE THREAD

**Issue by Dalojan** [pkourany/Arduino_Adafruit_mfGFX_Library#7]
Compiling a program for Arduino Mega 2560 is without problem but compiling for Arduino Due produces errors with respect to fonts.cpp 

C:\Users\jan\Documents\Arduino\libraries\Arduino_Adafruit_mfGFX\fonts.cpp:1953:1: error: too many initializers for 'const FontDescriptor'

There is no error while compiling the same source for Arduino Mega 2560

**Comment by pljakobs** [comment]
@Dalojan I have no Due, but this sounds odd, either there are too many initializers or there aren't. Could you upload your font file somewhere so that I could look at it?
